version: '3.4'

services:
  storeapi:
    image: ${DOCKER_REGISTRY-}storeapi
    build:
      context: .
      dockerfile: StoreApi/Dockerfile

  mailsenderapi:
    image: ${DOCKER_REGISTRY-}mailsenderapi
    container_name: mail_api
    build:
      context: .
      dockerfile: MailSenderApi/Dockerfile